#!/bin/bash

LOCAL_ENV_FILEPATH="/var/www/html/app/.env.local"

echo '## NOTE: This file will be re-generated by next DDEV start ##' > ${LOCAL_ENV_FILEPATH}
cat ../app/.env >> ${LOCAL_ENV_FILEPATH}
cat ../app/.env.ddev >> ${LOCAL_ENV_FILEPATH}
