### 
### Create author with all possible info
POST https://bookshelf.ddev.site/authors
Content-Type: application/json

{
    "firstname": "John",
    "middlename": "Ronald",
    "lastname": "Reuel",
    "books": [
        {
            "name": "Sunrise Nights 7",
            "short_description": "Two young artists have a chance meeting on the last night of summer arts camp in this YA novel in verse and dialogue cowritten by acclaimed authors Jeff Zentner and Brittany Cavallaro.",
            "published_at": "2024-07-10"
        },
        {
            "id": 6,
            "name": "Sunrise Nights 3"
        }
    ]
}

### 
### Create author with only first and last names
POST https://bookshelf.ddev.site/authors
Content-Type: application/json

{
    "firstname": "Susanna",
    "lastname": "Eloise"
}

### 
### Attempt of create author with only first name results into ERROR
POST https://bookshelf.ddev.site/authors
Content-Type: application/json

{
    "firstname": "John"
}

> {%
    client.test("Request is failed due to missing required fields", function() {
        client.assert(response.status !== 200, "Response status must be not 200");
    });
%}

### 
### Attempt of create author with last name less than 3 symbols results into ERROR
POST https://bookshelf.ddev.site/authors
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Th"
}

> {%
    client.test("Request is failed due to lastname field value being too short", function() {
        client.assert(response.status !== 200, "Response status must be not 200");
    });
%}

###
### Get authors specifying pagination
GET https://bookshelf.ddev.site/authors?limit=10&offset=0
Content-Type: application/json

###
### Get authors with books
GET https://bookshelf.ddev.site/authors?limit=20&offset=0&include_books=1
Content-Type: application/json
