### 
### Create book with all possible info
POST https://bookshelf.ddev.site/books
Content-Type: application/json

{
    "name": "Sunrise Nights 2",
    "short_description": "Two young artists have a chance meeting on the last night of summer arts camp in this YA novel in verse and dialogue cowritten by acclaimed authors Jeff Zentner and Brittany Cavallaro.",
    "published_at": "2024-07-09",
    "authors": [
        {
            "firstname": "Jeff",
            "lastname": "Zentner"
        },
        {
            "firstname": "Brittany",
            "lastname": "Cavallaro"
        }
    ]
}

### 
### Create book with existing authors
POST https://bookshelf.ddev.site/books
Content-Type: application/json

{
    "name": "The Last of August",
    "short_description": "In the second brilliant, action-packed book in the Charlotte Holmes series, Jamie Watson and Charlotte Holmes are in a chase across Europe to untangle a web of shocking truths about the Holmes and Moriarty families.",
    "published_at": "2018-02-06",
    "authors": [
        {
            "id": 2,
            "firstname": "Brittany",
            "lastname": "Cavallaro"
        }
    ]
}

###
### Get books using pagination
GET https://bookshelf.ddev.site/books?limit=10&include_authors=1
Content-Type: application/json

###
### Get a book by its ID
GET https://bookshelf.ddev.site/books/3?include_authors=1
Content-Type: application/json

### 
### Update existing book name
PUT https://bookshelf.ddev.site/books/3
Content-Type: application/json

{
    "name": "NEW The Last of August"
}

###
### Find books by author (full text search)
GET https://bookshelf.ddev.site/books/search/by_author?q=brittany
Content-Type: application/json

###
### Upload file with allowed file size & file type
POST https://bookshelf.ddev.site/books/image/1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="small-img1.jpg"
Content-Type: image/jpeg

< ./img/small-img1.jpg
--WebAppBoundary--

###
### Upload file with NOT allowed file type 
POST https://bookshelf.ddev.site/books/image/1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="text.txt"
Content-Type: text/plain

< ./img/text.txt
--WebAppBoundary--

> {%
    client.test("Request is failed due to unsupported file MIME type", function() {
        client.assert(response.status !== 200, "Response status must be not 200");
    });
%}

###
### Upload file with size above allowed
POST https://bookshelf.ddev.site/books/image/1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="big-img1.jpg"
Content-Type: image/jpeg

< ./img/big-img1.jpg
--WebAppBoundary--

> {%
    client.test("Request is failed due to too big file size", function() {
        client.assert(response.status !== 200, "Response status must be not 200");
    });
%}
