### 
### Create book with all possible info
POST https://bookshelf.ddev.site/books
Content-Type: application/json

{
    "name": "In the woods",
    "short_description": "this book is about something in the woods",
    "image": "/path/to/image.png",
    "published_at": "2022-02-23"
}

###
### Get books using pagination
GET https://bookshelf.ddev.site/books?include_authors=1
Content-Type: application/json